### ISSUE TITLE
Request letter

### ISSUE THREAD

**Issue by glorioushonor** [yxt7979/yxt7979#3]
Hello, I am a student from Tianjin University. I am glad to see that you have successfully reproduced the work of ICON. I have encountered some problems in the preprocessing stage of Thuman2.0 data set in the reproduction process, and I would like to discuss with you. I wonder if it is convenient for me to add my contact information.

**Comment by yxt7979** [comment]
> 

Hi，sure, what's your problems during the reproduction process? Could you please show me and I'll share my solution if I can!

**Comment by glorioushonor** [comment]
> > 
> 
> Hi，sure, what's your problems during the reproduction process? Could you please show me and I'll share my solution if I can!

Glad to receive your reply! Actually, I solved yesterday's problem. My problem was that I could not run the scripts "render_batch.py" and "visibility_batch.py" to get rendered data. The author modified this script in January, the author suggested to use the old version of the script, which is the script you run, and I am now able to run it successfully. (Thanks to the author, hhhh......🙇‍)
But I still have a few questions:
1. Check whether the bash scripts/vis_batch.sh gen all script is running slowly, I have run it for 3 hours.
2. Have you done all the replicating work, what GPU is supporting your replicating? My GPU is RTX 1080Ti.

**Comment by yxt7979** [comment]
Glad you have solved it! I set batch_size=8 with 20G GPU, I think RTX 1080Ti is okey!

**Comment by glorioushonor** [comment]
> > 
> 
> Hi，sure, what's your problems during the reproduction process? Could you please show me and I'll share my solution if I can!
![屏幕截图 2023-03-26 180749](https://user-images.githubusercontent.com/120625228/227769758-04abfbee-6144-4a3f-aab8-ce0f25bcefe3.jpg)

Hello, after data processing, I found the visualization results as follows:
![屏幕截图 2023-03-26 180749](https://user-images.githubusercontent.com/120625228/227769758-04abfbee-6144-4a3f-aab8-ce0f25bcefe3.jpg)
I have noticed that you have encountered the same problem, and you have solved it by redownloading SMPL-X,zip and unzip-o. But my SMPL-X is the latest download, could you please tell me some details?

**Comment by glorioushonor** [comment]
> Glad you have solved it! I set batch_size=8 with 20G GPU, I think RTX 1080Ti is okey!

Thank you for your reply. But that didn't seem to work. I tried to train it, and it said it was out of memory
